version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql2://root:proflow_password@db/proflow_production
      RAILS_ENV: production
    volumes:
      - ./storage:/rails/storage
    
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: proflow_password
      MYSQL_DATABASE: proflow_production
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 