version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - proflow-network
    command: --default-authentication-plugin=mysql_native_password

  web:
    build: .
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      RAILS_ENV: production
      DATABASE_URL: mysql2://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      RAILS_SERVE_STATIC_FILES: true
      RAILS_LOG_TO_STDOUT: true
    volumes:
      - ./storage:/rails/storage
      - ./log:/rails/log
    depends_on:
      - db
    networks:
      - proflow-network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/proflow.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/var/www/proflow/public:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web
    networks:
      - proflow-network

volumes:
  mysql_data:

networks:
  proflow-network:
    driver: bridge 